# MTH/CMSE 314  - Section 003 - Quiz 2

This is an open Internet quiz.  Feel free to use anything on the Internet with one important exception...

- **DO NOT** communicate live with other people during the quiz (either verbally or on-line).  The goal here is to find answers to problems as you would in the real world.  

You will be given **20 minutes** to complete this quiz.  Use your time wisely. 

**HINTS:**
- Neatness and grammar is important.  We will ignore all notes or code we can not read or understand.
- Read the entire quiz from beginning to end before starting.  Not all questions are equal in **points vs. time** so plan your time accordingly.   
- Some of the information provided my be a distraction. Do not assume you need to understand everything written to answer the questions. 
- Spaces for answers are provided. Delete the prompting text such as "Put your answer to the above question here" and replace it with your answer. Do not leave the prompting text with your answer.
- Do not assume that the answer must be in the same format of the cell provided. Feel free to change the cell formatting (e.g., markdown to code, and vice versa) or add additional cells as needed to provide your answer.
- When a question asks for an answer "**in your own words**" it is still okay to search the Internet for the answer as a reminder. *However*, we would like you to do more than cut and paste.  Make the answer your own. 
- If you get stuck, try not to leave an answer blank. It is better to include some notes or stub functions so we have an idea about your thinking process so we can give you partial credit.   
- Always provid links to any references you find helpful. 
- Feel free to delete the provided check marks (&#9989;) as a way to keep track of which questions you have successfully completed. 


# Honor Code

I, agree to neither give nor receive any help on this quiz from other people.  I also understand that providing answers to questions on this quiz to other students is also an academic misconduct violation as is live communication or receiving answers to questions on this quiz from other people. It is important to me to be a person of integrity and that means that ALL ANSWERS on this quiz are my answers.

&#9989; **<font color=red>DO THIS:</font>** Include your name in the line below to acknowledge the above statement:

Put your name here.

# Download Automatic Answer Check

This quiz may require an automated answer checking system for grading.  The following cell will automatically download the latest version of the answer checker. 

In [1]:
from urllib.request import urlretrieve

urlretrieve('https://raw.githubusercontent.com/colbrydi/jupytercheck/master/answercheck.py', 
            'answercheck.py');

Verify you have Check Answer installed by running the following cell

In [2]:
from answercheck import checkanswer
checkanswer("Check Answer",'bd8337cd5327e54b2b4b15c6ec3703ed');

Testing Check Answer
Answer seems to be correct



In [3]:
%matplotlib inline 
import math
import numpy as np
import sympy as sym
import matplotlib.pyplot as plt
sym.init_printing()

## Motivating problem: QR decomposition

QR decomposition is a widely used algorithm in solving the least squares problem and the eigenvalue problem. The goal of the QR decomposition is to rewrite a matrix $A\in\mathbb{R}^{m\times n}\; (m\geq n)$ as
$$
\begin{align}
A & = QR\\
  & = Q\begin{pmatrix}
        r_{11} & r_{12} & r_{13} & \cdots & r_{1n}\\
        0      & r_{22} & r_{23} & \cdots & r_{2n}\\
        0      & 0      & r_{33} & \cdots & r_{3n}\\
        \vdots &\vdots  & \vdots & \vdots& \vdots\\
        0      &0       &  0     & \cdots& r_{nn}\\
        0      &0       &  0     & \cdots& 0     \\
        \vdots &\vdots  & \vdots & \vdots& \vdots\\
        0      &0       &  0     & \cdots& 0     \\
       \end{pmatrix}
\end{align}
$$
Here, $Q$ is an orthogonal matrix (you do not need to understand the meaning of this) and $R$ is an upper triangular matrix.

One way to compute $Q$ and $R$ is to utilize  **_Givens rotation_** (a special rotation transformation). We will present the idea with small square matrices.


Consider a vector 
$$
\begin{pmatrix}
a\\
b
\end{pmatrix}
$$
with $a \neq 0, b\neq 0$.

The corresponding **_Givens rotation_** is to rotate the vector with angle
$$
\theta = -arctan\left(\frac{a}{b}\right).
$$



&#9989;  **<font color=red>QUESTION 1:</font>** Given the vector
$
v = \begin{pmatrix}
1 \\
1
\end{pmatrix}
$ and its corresponding angle $\theta = -\frac{\pi}{4}$. Define a rotation matrix $G$ corresponding to the **_Givens_** transformation.
(5 pts)


In [4]:
# Put your answer to the above question here

v = np.matrix([ [1],[1] ])
theta = -np.arctan(1/1)
T = np.matrix([[np.cos(theta),-np.sin(theta)],[np.sin(theta),np.cos(theta)]])

In [5]:
from answercheck import checkanswer

checkanswer.matrix(T,"79d88d28a0f634a846ebb7b5e06a62a4");

Testing [[ 0.70711  0.70711]
 [-0.70711  0.70711]]
Answer seems to be correct



----

Now Consider the following $3 \times 3$ matrix:
$$
A = \begin{pmatrix}
1 & \sqrt{3} & 3 \\
-\sqrt{3} & 1 & 3 \\
0 & 2 & 6
\end{pmatrix}.
$$
To obtain the QR decomposition, we can apply two **_Givens rotation_** transformations $G_1$ and $G_2$. 

The first rotation $G_1$ is **rotate the vector around z-axis anti-clock wise with angle $\frac{\pi}{3}$**. 


&#9989;  **<font color=red>QUESTION 2:</font>**  Define $G_1$ in the numpy format. (5pts)

**<font color=red>Hint:</font>** $G_1$ is also a $3 \times 3$ matrix.


In [17]:
# Put your answer to the above question here

angle = math.pi/3 # already in radians
G1 = np.matrix([[np.cos(angle),-np.sin(angle),0],[np.sin(angle),np.cos(angle),0],[0,0,1]])
#A=np.matrix([[1,math.sqrt(3),3],[-math.sqrt(3),1,3],[0,2,6]])


In [18]:
from answercheck import checkanswer

checkanswer.matrix(G1,"10e0d5483fd7ef4570639297348a8c88");


    Converting to positive values of zero using  ```A[A==-0] = 0```.

Testing [[ 0.5     -0.86603  0.     ]
 [ 0.86603  0.5      0.     ]
 [ 0.       0.       1.     ]]
Answer seems to be correct



----

The second **_Givens rotation_** $G_2$ is defined using the following matrix:
$$
G_2 = \begin{pmatrix}
1 & 0 & 0\\
0 &\cos(-\frac{\pi}{4}) &   -\sin(-\frac{\pi}{4})  \\
0 &\sin(-\frac{\pi}{4}) &   -\cos(-\frac{\pi}{4}) 
\end{pmatrix}.
$$

Given $G_1$ and $G_2$ we can calculate the $R$ and $Q$ matrices for $A$ using the following:
$$
R = G_2 G_1 A
$$
and
$$ Q = G_1^T G_2^T.$$ Here, $G_1^T$ and $G_2^T$ are the transpose of $G_1$ and $G_2$.

&#9989;  **<font color=red>QUESTION 3:</font>**  (5 points) Calculate $R$ and $Q$ with matrix multiplications. Calculate the determinant of $A$. (5 pts = 1pts for R+2pts for Q+2pts for determinant of A)

In [27]:
A = np.matrix([ [1,math.sqrt(3),3],[-math.sqrt(3),1,3],[0,2,6 ] ])

angle_g2 = -math.pi/4
G2 = np.matrix( [ [1,0,0],[0,math.cos(angle_g2),-math.sin(angle_g2)],[0,math.sin(angle_g2),math.cos(angle_g2)] ])
##############################################
# Put your answer to the above question here
##############################################
R = G2@G1@A
Q = G1.transpose()@G2.transpose()
A_det =np.linalg.det(A)
 
##############################################
# show the results
print('Matrix R:\n',R)
print('Matrix Q:\n',Q)
print('Determinant of A:\n',A_det)
#np.allclose(Q*R,A)

Matrix R:
 [[ 2.00000000e+00  2.22044605e-16 -1.09807621e+00]
 [ 0.00000000e+00  2.82842712e+00  7.14041817e+00]
 [ 1.11022302e-16  2.22044605e-16  1.34486321e+00]]
Matrix Q:
 [[ 0.5         0.61237244 -0.61237244]
 [-0.8660254   0.35355339 -0.35355339]
 [ 0.          0.70710678  0.70710678]]
Determinant of A:
 7.6076951545867315


In [28]:
checkanswer.matrix(R,"c5b8b46e06b1acddfa73d7a2fc5f1935");


    Converting to positive values of zero using  ```A[A==-0] = 0```.

Testing [[ 2.       0.      -1.09808]
 [ 0.       2.82843  7.14042]
 [ 0.       0.       1.34486]]
Answer seems to be correct



In [29]:
checkanswer.matrix(Q,"c14574035147bc9df310a4aa035fdeff");


    Converting to positive values of zero using  ```A[A==-0] = 0```.

Testing [[ 0.5      0.61237 -0.61237]
 [-0.86603  0.35355 -0.35355]
 [ 0.       0.70711  0.70711]]
Answer seems to be correct



In [30]:
checkanswer.matrix(A_det,"69622cf97379b9fff413cc2b59214fa9");


    Trying to convert to a array matrix using ```A = np.matrix(A)```.

Testing [[7.6077]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 4:</font>**  Can we exchange the order of applying the two **_Givens rotations_** in the above procedure? Why? (2pts)

**Put your answer here:** 









&#9989;  **<font color=red>QUESTION 5:</font>**  Use Python to calcualte the inverse of $A$. (5pts)

In [32]:
# Put your answer to the above question here
A_inv = np.linalg.inv(A)

In [33]:
checkanswer.matrix(A_inv,"f491a95f3aa006965d36493ad18bd631");


    Converting to positive values of zero using  ```A[A==-0] = 0```.

Testing [[ 0.      -0.57735  0.28868]
 [ 1.36603  0.78868 -1.07735]
 [-0.45534 -0.26289  0.52578]]
Answer seems to be correct



&#9989;  **<font color=red>QUESTION 6:</font>**  What is the elementry matrix corresponding to **add 3 times the first row to the third row**? Modify the 3 by 3 matrix below to answer this question. (3pts)

In [36]:
# Put your answer to the above question here
E=np.matrix([[1,0,0],[0,1,0],[3,0,1]])

In [37]:
checkanswer.matrix(E,"55ae1f9eb21df00c59dad623b9471506");


    Trying to convert to float using ```A = A.astype(float)```.


    Converting to positive values of zero using  ```A[A==-0] = 0```.

Testing [[1. 0. 0.]
 [0. 1. 0.]
 [3. 0. 1.]]
Answer seems to be correct



---------
### Congratulations, you're done with your QUIZ

Now, you just need to submit this assignment by uploading it to the course [Desire2Learn](http://d2l.msu.edu) web page for today's dropbox.

&#9989; **<font color=red>DO THIS:</font>**
- Download the Notebook to your desktop with the filename using the format **"NETID-Quiz2.ipynb"**.  Replace **NETID** in the filename with your personal MSU NetID (the stuff that comes before the @ symbol in your msu email address).
- Upload the newly renamed notebook to the D2L dropbox. (improper naming of your notebook may cause points to be taken away).



Written by Dr. Zhichao Peng, Michigan State University
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.